@url_dev= http://localhost:3052/v1/api

###signUp

# POST  {{url_dev}}/shop/login
# POST {{url_dev}}/product/publish/648758e96bb0b3902eb54a3d
# POST {{url_dev}}/product
PATCH {{url_dev}}/product/648758e96bb0b3902eb54a3d
# GET  {{url_dev}}/product/drafts/all
# GET {{url_dev}}/product/findbyid/648758e96bb0b3902eb54a3d
Content-Type: application/json
x-api-key : 74f7de29dca768cca482da72a925dfced4ee6a744b3b087b9d630bfac3ca163906ccccf7084b76d2bc8e80bcd404dd1c43bc7c4b3fbf1eef50e66485de5f252c
x-client-id: 647ed6cc3ac55a7f5842b8f6
# # x-rtoken-id: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDgyZTBiZjVhNmI0NGE3NWRiYWI5ZTIiLCJlbWFpbCI6InR1bmFrYXkxMjM0NUBhYmMuY29tIiwiaWF0IjoxNjg2MzgyODc2LCJleHAiOjE2ODY5ODc2NzZ9.5lRiI2X5szDnl91EPdvf2LDAdNXPkxm7zf42RJoX8sI
# authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDdlZDZjYzNhYzU1YTdmNTg0MmI4ZjYiLCJlbWFpbCI6ImFiYzEyMzRAYWJjLmNvbSIsImlhdCI6MTY4NjczNDgwMCwiZXhwIjoxNjg2OTA3NjAwfQ.IUym9tCFQ1NMVo16XcCduj5k7JwSjuhEi19Z-gEfzMw

{ 
  "product_name": "Áo chống thấm nước thương hiệu Việt Nam updated 2",
    "product_thumb": "abc.jpg",
    "product_description": "áo đucợ làm từ chất liệu vải dù khô thoáng, ngăn nước dù chỉ là những hạt nước nhỏ bé",
    "product_price": null,
    "product_quantity": 12333,
    "product_type": "Clothing",
    "product_shop": "6482e0bf5a6b44a75dbab9e2",
    "product_attributes": {
      "brand": "ABC updated",
      "size": null,
      "material": "cotton 2"
    }
}
