@url_dev= http://localhost:3052/v1/api
@url_api = http://localhost:3052

###api-docs
GET {{url_api}}/api-docs

{}


### SigUp
POST {{url_dev}}/shop/signUp
Content-Type: application/json
x-api-key : 74f7de29dca768cca482da72a925dfced4ee6a744b3b087b9d630bfac3ca163906ccccf7084b76d2bc8e80bcd404dd1c43bc7c4b3fbf1eef50e66485de5f252c

{
  "name": "abcaa",
  "email": "abcaaa@gmail.com",
  "password": "abc1234"
}

### Login
POST {{url_dev}}/k
Content-Type: application/json
x-api-key : 74f7de29dca768cca482da72a925dfced4ee6a744b3b087b9d630bfac3ca163906ccccf7084b76d2bc8e80bcd404dd1c43bc7c4b3fbf1eef50e66485de5f252c

{ 
  "email": "abc123@abc.com",
  "password": "abc123"
}


### GET product: allDraft, all publish, find by id
# GET  {{url_dev}}/product/drafts/all 
GET  {{url_dev}}/product/published/all
# GET {{url_dev}}/product/findbyid/648758e96bb0b3902eb54a3d
Content-Type: application/json
x-api-key :74f7de29dca768cca482da72a925dfced4ee6a744b3b087b9d630bfac3ca163906ccccf7084b76d2bc8e80bcd404dd1c43bc7c4b3fbf1eef50e66485de5f252c
x-client-id: 647ed6cc3ac55a7f5842b8f6
# x-rtoken-id: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDgyZTBiZjVhNmI0NGE3NWRiYWI5ZTIiLCJlbWFpbCI6InR1bmFrYXkxMjM0NUBhYmMuY29tIiwiaWF0IjoxNjg2MzgyODc2LCJleHAiOjE2ODY5ODc2NzZ9.5lRiI2X5szDnl91EPdvf2LDAdNXPkxm7zf42RJoX8sI
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDdlZDZjYzNhYzU1YTdmNTg0MmI4ZjYiLCJlbWFpbCI6ImFiYzEyMzRAYWJjLmNvbSIsImlhdCI6MTY5MzM5NTE5NiwiZXhwIjoxNjkzNTY3OTk2fQ.XeGv6BH-vUf6-C8bK1bjOo14Y5GppimGnT8tU5jEv8A

{}


### publish and unpublish Product
POST {{url_dev}}/product/publish/648fe0b59597d81ba3dd1356
# POST {{url_dev}}/product/unpublish/648758e96bb0b3902eb54a3d
Content-Type: application/json
x-api-key :74f7de29dca768cca482da72a925dfced4ee6a744b3b087b9d630bfac3ca163906ccccf7084b76d2bc8e80bcd404dd1c43bc7c4b3fbf1eef50e66485de5f252c
x-client-id: 647ed6cc3ac55a7f5842b8f6
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDdlZDZjYzNhYzU1YTdmNTg0MmI4ZjYiLCJlbWFpbCI6ImFiYzEyMzRAYWJjLmNvbSIsImlhdCI6MTY4OTg0MDgwMywiZXhwIjoxNjkwMDEzNjAzfQ.RM9M9hxl-6gEw3K_JpBPndYEtmylmULK6Q-laO6I_BA

{}

### create Product
POST {{url_dev}}/product
Content-Type: application/json
x-api-key :74f7de29dca768cca482da72a925dfced4ee6a744b3b087b9d630bfac3ca163906ccccf7084b76d2bc8e80bcd404dd1c43bc7c4b3fbf1eef50e66485de5f252c
x-client-id: 647ed6cc3ac55a7f5842b8f6
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDdlZDZjYzNhYzU1YTdmNTg0MmI4ZjYiLCJlbWFpbCI6ImFiYzEyMzRAYWJjLmNvbSIsImlhdCI6MTY5MTkzOTIzNSwiZXhwIjoxNjkyMTEyMDM1fQ.zNu74qptGtPx-BWzjf529q-Y5wZFefw7GxnN0fpsrPI

{ 
  "product_name": "Áo khoác ngoài nhap khau",
    "product_thumb": "abc.jpg",
    "product_description": "áo đuoc làm từ chất liệu vải dù khô thoáng, ngăn nước dù chỉ là những hạt nước nhỏ bé",
    "product_price": 54000,
    "product_quantity": 444,
    "product_type": "Clothing",
    "product_attributes": {
      "brand": "ABC 123",
      "size": "XXL",
      "material": "cotton 2"
    }
}

### update product
PATCH {{url_dev}}/product/648bda529cbcb91ed8642ec7
Content-Type: application/json
x-api-key :74f7de29dca768cca482da72a925dfced4ee6a744b3b087b9d630bfac3ca163906ccccf7084b76d2bc8e80bcd404dd1c43bc7c4b3fbf1eef50e66485de5f252c
x-client-id: 647ed6cc3ac55a7f5842b8f6
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDdlZDZjYzNhYzU1YTdmNTg0MmI4ZjYiLCJlbWFpbCI6ImFiYzEyMzRAYWJjLmNvbSIsImlhdCI6MTY4OTg0MDgwMywiZXhwIjoxNjkwMDEzNjAzfQ.RM9M9hxl-6gEw3K_JpBPndYEtmylmULK6Q-laO6I_BA

{ 
  "product_name": "Áo khoác ngoài hàng nhật",
    "product_thumb": "abc.jpg",
    "product_description": "áo đucợ làm từ chất liệu vải dù khô thoáng, ngăn nước dù chỉ là những hạt nước nhỏ bé",
    "product_price": 40000,
    "product_quantity": 12333,
    "product_type": "Clothing",
    "product_attributes": {
      "brand": "ABC updated",
      "size": "XLL",
      "material": "cotton 2"
    }
}

###Discount
#------------------
###Create Discount
POST {{url_dev}}/discount
Content-Type: application/json
x-api-key :74f7de29dca768cca482da72a925dfced4ee6a744b3b087b9d630bfac3ca163906ccccf7084b76d2bc8e80bcd404dd1c43bc7c4b3fbf1eef50e66485de5f252c
x-client-id: 647ed6cc3ac55a7f5842b8f6
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDdlZDZjYzNhYzU1YTdmNTg0MmI4ZjYiLCJlbWFpbCI6ImFiYzEyMzRAYWJjLmNvbSIsImlhdCI6MTY4OTg0MDgwMywiZXhwIjoxNjkwMDEzNjAzfQ.RM9M9hxl-6gEw3K_JpBPndYEtmylmULK6Q-laO6I_BA

{ 
"name": "Coupon 50K",
"description": "Giam 50k",
"type": "fixed_amount",
"value":50000,
"max_value": 50000,
"code": "SHOPTUNA-50K",
"start_date": "2023-07-21 09:00:00",  
"end_date": "2023-08-21 09:00:00",  
"max_uses": 100,
"uses_count": 0,
"users_used": [],
"max_uses_per_user": 1,
"min_order_value": 200000,
"is_active": true,
"applies_to": "all",
"product_ids": ["648825f28cbf7c9ef56c0197","648758e96bb0b3902eb54a3d"]

}

#------------------
###Get All products with discountCode 
GET {{url_dev}}/discount/list_product_code?code=SHOPTUNA-5555&shopId=647ed6cc3ac55a7f5842b8f6
Content-Type: application/json
x-api-key : 74f7de29dca768cca482da72a925dfced4ee6a744b3b087b9d630bfac3ca163906ccccf7084b76d2bc8e80bcd404dd1c43bc7c4b3fbf1eef50e66485de5f252c

{}

#------------------
###Get amount when applies discount
POST {{url_dev}}/discount/amount
Content-Type: application/json
x-api-key :74f7de29dca768cca482da72a925dfced4ee6a744b3b087b9d630bfac3ca163906ccccf7084b76d2bc8e80bcd404dd1c43bc7c4b3fbf1eef50e66485de5f252c

{
"code":"SHOPTUNA-40K",
"userId": 2,
"shopId": "647ed6cc3ac55a7f5842b8f6",
"products":[
  {
    "productId":"648bda529cbcb91ed8642ec7",
    "quantity": 10,
    "price": 30000
  }
]
}

###Cart
### Add to cart
POST {{url_dev}}/cart
Content-Type: application/json
x-api-key :74f7de29dca768cca482da72a925dfced4ee6a744b3b087b9d630bfac3ca163906ccccf7084b76d2bc8e80bcd404dd1c43bc7c4b3fbf1eef50e66485de5f252c
{
"userId": 400,
"product":
  {
    "productId":"648bda529cbcb91ed8642ec7",
    "quantity": 12
  }
}

### Delete cart item
DELETE {{url_dev}}/cart
Content-Type: application/json
x-api-key :74f7de29dca768cca482da72a925dfced4ee6a744b3b087b9d630bfac3ca163906ccccf7084b76d2bc8e80bcd404dd1c43bc7c4b3fbf1eef50e66485de5f252c

{
"userId": 400,
"productId":"6489273fe2373cd40ee5ca87"

}

### Get list cart item
GET {{url_dev}}/cart?userId=400
Content-Type: application/json
x-api-key :74f7de29dca768cca482da72a925dfced4ee6a744b3b087b9d630bfac3ca163906ccccf7084b76d2bc8e80bcd404dd1c43bc7c4b3fbf1eef50e66485de5f252c

{
"userId": 400
}

### update cart item
POST {{url_dev}}/cart/update
Content-Type: application/json
x-api-key :74f7de29dca768cca482da72a925dfced4ee6a744b3b087b9d630bfac3ca163906ccccf7084b76d2bc8e80bcd404dd1c43bc7c4b3fbf1eef50e66485de5f252c

{
  "userId": 400,
"shop_order_ids" :[
  {
   "shopId": "647ed6cc3ac55a7f5842b8f6",
    "item_products":
    [
      {
           "quantity" : 12,
           "shopId": "647ed6cc3ac55a7f5842b8f6" ,
           "old_quantity": 62,
           "productId": "648bda529cbcb91ed8642ec7"
    }
   ]
    ,
    "version": 203
  }
]
}


### checkout review
POST {{url_dev}}/checkout/review 
Content-Type: application/json
x-api-key :74f7de29dca768cca482da72a925dfced4ee6a744b3b087b9d630bfac3ca163906ccccf7084b76d2bc8e80bcd404dd1c43bc7c4b3fbf1eef50e66485de5f252c

  #  cartId,
  #  userId,
  #      shop_order_ids:[
  #      shopId,
  #      shop_discount: {
  #            shopId,
  #            discountId,
  #            codeId
  #      },
  #      item_products: [
  #                  {
  #                  price,
  #                  quantity,
  #                  productId
  #                  }
  #               ]
  #      ]
{
  "cartId": "64926ec6f42f1e22a7fddfab",
  "userId": 400,
  "shop_order_ids" :[
  {
   "shopId": "6482e0bf5a6b44a75dbab9e2",
    "item_products":
    [
      {
           "quantity" : 29,
           "price": "333",
           "productId": "648825f28cbf7c9ef56c0197"
     }
   ],
   "shop_discount": []
  }
]
}

### Test redis
GET  {{url_dev}}/redis
Content-Type: application/json
x-api-key :74f7de29dca768cca482da72a925dfced4ee6a744b3b087b9d630bfac3ca163906ccccf7084b76d2bc8e80bcd404dd1c43bc7c4b3fbf1eef50e66485de5f252c

{}


### create comment
POST {{url_dev}}/comment
Content-Type: application/json
x-api-key :74f7de29dca768cca482da72a925dfced4ee6a744b3b087b9d630bfac3ca163906ccccf7084b76d2bc8e80bcd404dd1c43bc7c4b3fbf1eef50e66485de5f252c
x-client-id: 647ed6cc3ac55a7f5842b8f6
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDdlZDZjYzNhYzU1YTdmNTg0MmI4ZjYiLCJlbWFpbCI6ImFiYzEyMzRAYWJjLmNvbSIsImlhdCI6MTY5MTQ4OTA5NiwiZXhwIjoxNjkxNjYxODk2fQ.EWs3jYUDffOc5qBoiJwOQFpWbR4WBPk1UlfKiHLtx3M

# {
#     "productId" : "648fe0b59597d81ba3dd1356" ,
#      "userId" :  400 , 
#      "content":  "Comment 1" ,
#      "parentCommentId": null
# }

{
    "productId" : "648fe0b59597d81ba3dd1356" ,
     "userId" :  400 , 
     "content":  "Comment 1.1.3.1" ,
     "parentCommentId": "64d440827070830eb069c7ff"
}


### get comment
GET {{url_dev}}/comment
Content-Type: application/json
x-api-key :74f7de29dca768cca482da72a925dfced4ee6a744b3b087b9d630bfac3ca163906ccccf7084b76d2bc8e80bcd404dd1c43bc7c4b3fbf1eef50e66485de5f252c
x-client-id: 647ed6cc3ac55a7f5842b8f6
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDdlZDZjYzNhYzU1YTdmNTg0MmI4ZjYiLCJlbWFpbCI6ImFiYzEyMzRAYWJjLmNvbSIsImlhdCI6MTY5MTQ4OTA5NiwiZXhwIjoxNjkxNjYxODk2fQ.EWs3jYUDffOc5qBoiJwOQFpWbR4WBPk1UlfKiHLtx3M

{
  "productId": "648fe0b59597d81ba3dd1356",
  "parentCommentId": "64d440827070830eb069c7ff"
}

### delete comments
DELETE  {{url_dev}}/comment
Content-Type: application/json
x-api-key :74f7de29dca768cca482da72a925dfced4ee6a744b3b087b9d630bfac3ca163906ccccf7084b76d2bc8e80bcd404dd1c43bc7c4b3fbf1eef50e66485de5f252c
x-client-id: 647ed6cc3ac55a7f5842b8f6
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDdlZDZjYzNhYzU1YTdmNTg0MmI4ZjYiLCJlbWFpbCI6ImFiYzEyMzRAYWJjLmNvbSIsImlhdCI6MTY5MTQ4OTA5NiwiZXhwIjoxNjkxNjYxODk2fQ.EWs3jYUDffOc5qBoiJwOQFpWbR4WBPk1UlfKiHLtx3M

{
  "productId": "648fe0b59597d81ba3dd1356",
  "commentId": "64d440827070830eb069c7ff"
}

### Get Notification By User
GET {{url_dev}}/notification
Content-Type: application/json
x-api-key :74f7de29dca768cca482da72a925dfced4ee6a744b3b087b9d630bfac3ca163906ccccf7084b76d2bc8e80bcd404dd1c43bc7c4b3fbf1eef50e66485de5f252c
x-client-id: 647ed6cc3ac55a7f5842b8f6
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDdlZDZjYzNhYzU1YTdmNTg0MmI4ZjYiLCJlbWFpbCI6ImFiYzEyMzRAYWJjLmNvbSIsImlhdCI6MTY5MTkzOTIzNSwiZXhwIjoxNjkyMTEyMDM1fQ.zNu74qptGtPx-BWzjf529q-Y5wZFefw7GxnN0fpsrPI

{
}